apiVersion: v1
kind: Service
metadata:
  name: simpleapp-front
spec:
  selector:
    app: simpleapp
    tier: front
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
