apiVersion: apps/v1
kind: Deployment
metadata:
  name: now-deployment
  labels:
    app: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
      tier: now
  template:
    metadata:
      labels:
        app: simpleapp
        tier: now
    spec:
      containers:
        - name: now
          image: 685630748653.dkr.ecr.eu-west-1.amazonaws.com/simpleapp:latest
          command: ['/usr/bin/python3', '/app/simpleapp/svc_now.py']
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /now
              port: http
          readinessProbe:
            httpGet:
              path: /now
              port: http
          env:
            - name: SAPP_REDIS_URL
              value: redis://redis
