# Default values for simpleapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontCount: 2
nowCount: 1
timefmtCount: 1

image:
  repository: 685630748653.dkr.ecr.eu-west-1.amazonaws.com/simpleapp
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
